services:
  backend:
    build:
      context: ./backend
    container_name: backend_container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./docs-react
    container_name: frontend_container
    ports:
      - "3000:3000"
    volumes:
      - ./docs-react:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
